### PR TITLE
New approach with Play Framework in the server side

### PR DESCRIPTION
**Pull request by rafaparadela**
@raulraja Please, take a look to this project: https://github.com/47deg/scala-js-demo/tree/play-framework-server-side

The simplest PlayFramework scaffolding possible with Scala.js integrated. Let me know you thoughts.

Thank you.

### CODE REVIEW

**Comment by rafaparadela** [comment]
@raulraja FYI: The project has been deployed at http://shrouded-forest-7969.herokuapp.com/ (Since the distribution package isn't valid for GitHub Pages anymore).

**Comment by raulraja** [comment]
LGTM, great work!

**Comment by nickelsberry** [comment]
Language reviewed and ready to deploy

**Comment by rafaparadela** [comment]
Shipping th boat...

**Pull request merged**
